# Generated by Django 3.0.3 on 2020-07-03 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=256)),
                ('alcohol_content', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('halal_status', models.CharField(choices=[('Contains alcohol', 'Contains alcohol'), ('Inconsistent data', 'Inconsistent data'), ('Halal suitable', 'Halal suitable'), ('Not Halal', 'Not Halal')], default='Halal Suitable', max_length=256)),
            ],
        ),
    ]
