# Generated by Django 3.0.3 on 2020-07-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_status', models.CharField(choices=[('FS', 'FS'), ('CR', 'CR'), ('CC', 'CC'), ('CE', 'CE'), ('CD', 'CD'), ('CT', 'CT')], max_length=256)),
                ('portfolio_manager', models.CharField(max_length=256)),
            ],
        ),
    ]
