# Generated by Django 3.0.3 on 2020-07-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalInfo',
        ),
    ]
