# Generated by Django 3.0.3 on 2020-07-03 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('order_date', models.DateField(default=datetime.datetime.today)),
                ('arrival_date', models.DateField()),
                ('lab_location', models.CharField(max_length=256)),
            ],
        ),
    ]
