# Generated by Django 3.0.3 on 2020-07-05 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='order_date',
            field=models.DateField(default=datetime.datetime.today, null=True),
        ),
    ]
