# Generated by Django 3.0.3 on 2020-07-05 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200705_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='arrival_date',
            field=models.DateField(default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime.today, null=True),
        ),
    ]
