# Generated by Django 3.0.3 on 2020-07-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20200705_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='arrival_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='expiry_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='order_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
