# Generated by Django 3.0.3 on 2020-07-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200710_1457'),
        ('stock', '0005_auto_20200705_1922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
