# Generated by Django 3.0.3 on 2020-07-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_form', models.CharField(choices=[('Liquid', 'Liquid'), ('Spray Dried', 'Spray Dried'), ('Viscous/Paste', 'Viscous/Paste'), ('Wash', 'Wash')], max_length=256)),
                ('solubility', models.CharField(choices=[('Oil soluble', 'Oil soluble'), ('Water soluble', 'Water soluble'), ('Water dispersible', 'Water dispersable')], max_length=256)),
                ('shelf_life', models.PositiveIntegerField()),
                ('storage_condition', models.CharField(max_length=256)),
                ('production_site', models.CharField(choices=[('Holzminden', 'Holzminden'), ('Noerdlingen', 'Noerdlingen'), ('Braunschweig', 'Braunschweig'), ('Egypt', 'Egypt')], max_length=256)),
            ],
        ),
    ]
