# Generated by Django 3.0.3 on 2020-07-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical_info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechnicalInfo',
        ),
    ]
