# Generated by Django 3.0.3 on 2020-07-03 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wlc', models.BooleanField(verbose_name='Winning Local Collection')),
                ('six_digit_code', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
                ('name', models.CharField(max_length=256)),
                ('flavour_key', models.CharField(max_length=256)),
            ],
        ),
    ]
