# Generated by Django 3.0.3 on 2020-07-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_info', '0001_initial'),
        ('additional_info', '0001_initial'),
        ('technical_info', '0001_initial'),
        ('stock', '0001_initial'),
        ('products', '0002_auto_20200705_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additonal_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='additional_info.AdditionalInfo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regulatory_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='regulatory_info.RegulatoryInfo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='stock.Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='technical_info.TechnicalInfo'),
        ),
    ]
