# Generated by Django 3.0.3 on 2020-07-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200712_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
