# Generated by Django 3.0.3 on 2020-07-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200712_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='halal_status',
            field=models.CharField(choices=[('Contains alcohol', 'Contains alcohol'), ('Inconsistent data', 'Inconsistent data'), ('Halal suitable', 'Halal suitable'), ('Not Halal', 'Not Halal')], default='Halal Suitable', max_length=256, null=True),
        ),
    ]
