# Generated by Django 3.0.3 on 2020-07-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200713_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='legal_name',
            field=models.CharField(choices=[('FLAVOURING', 'FLAVOURING'), ('NATURAL FLAVOURING', 'NATURAL FLAVOURING')], max_length=256, null=True),
        ),
    ]
