# Generated by Django 3.0.3 on 2020-07-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200715_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, null=True, unique=True),
        ),
    ]
