# Generated by Django 3.0.3 on 2020-07-15 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200715_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alcohol_content',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Alcohol content ( in % )'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.PositiveIntegerField(null=True, verbose_name='Shelf life ( in days )'),
        ),
    ]
