# Generated by Django 3.0.3 on 2020-07-18 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200715_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alcohol_content',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Alcohol content ( in % )'),
        ),
    ]
