# Generated by Django 3.0.3 on 2020-07-26 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200718_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity ( in g )'),
        ),
    ]
