# Generated by Django 3.0.3 on 2020-08-01 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200726_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='six_digit_code',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)]),
        ),
    ]
